from kitti_model_config import kitti_model_config
from kitti_vgg16_config import kitti_vgg16_config
from kitti_res50_config import kitti_res50_config
from kitti_squeezeDet_config import kitti_squeezeDet_config
from kitti_squeezeDet_FPN_config import kitti_squeezeDet_FPN_config
from kitti_squeezeDetPlus_config import kitti_squeezeDetPlus_config
from kitti_zynqDet_config import kitti_zynqDet_config
from kitti_zynqDet_FPN_config import kitti_zynqDet_FPN_config
