from squeezeDet import SqueezeDet
from squeezeDet_FPN import SqueezeDet_FPN
from squeezeDetPlus import SqueezeDetPlus
from resnet50_convDet import ResNet50ConvDet
from vgg16_convDet import VGG16ConvDet
from zynqDet import ZynqDet
from zynqDet_FPN import ZynqDet_FPN
from zynqDet_FPN_Quant import ZynqDet_FPN_Quant
from tinyDarkNet_FPN import tinyDarkNet_FPN
